# Site settings
title: MPV Productions
email: malona@bade.lt
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mpvprod.com" # the base hostname & protocol for your site
twitter_username: mpvprod
github_username:  mpvprod

# Build settings
markdown: kramdown
